---
- name: Create certs directory if it does not exist
  file:
    path: /etc/nginx/ssl-certs
    state: directory
    mode: '0755'

- name: Add ssl cert
  template:
    src: example.cert.j2
    dest: /etc/nginx/ssl-certs/example.cert

- name: Add ssl cert key
  template:
    src: example.key.j2
    dest: /etc/nginx/ssl-certs/example.key

- name: Install nginx Debian
  block:
    - name: Add nginx repository
      apt_repository:
        repo: ppa:nginx/stable  # it should be internal repo
        state: present
    - name: Install nginx
      apt:
        pkg: nginx
        state: present
        update_cache: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install nginx RedHat
  block:
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present
        update_cache: true
    - name: Install nginx
      yum:
        name: nginx
        state: present
        update_cache: true
    - name: Enable nginx service
      systemd:
        name: nginx
        state: started
        daemon_reload: yes
        enabled: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'
