# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

# ENV ANSIBLE_USER=ansible SUDO_GROUP=wheel DEPLOY_GROUP=deployer
# RUN set -xe \
#   && groupadd -r ${ANSIBLE_USER} \
#   && groupadd -r ${DEPLOY_GROUP} \
#   && useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} \
#   && usermod -aG ${SUDO_GROUP} ${ANSIBLE_USER} \
#   && usermod -aG ${DEPLOY_GROUP} ${ANSIBLE_USER} \
#   && sed -i "/^%${SUDO_GROUP}/s/ALL\$/NOPASSWD:ALL/g" /etc/sudoers

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y python sudo bash ca-certificates && apt-get clean; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y python sudo yum-plugin-ovl bash && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; fi
