---
- name: Check if version directory exists.
  stat:
    path: "{{ app_dest }}/{{ app_version }}"
  register: file_details

- name: Pull repository from github
  git:
    repo: "{{ app_repository }}"
    dest: "{{ app_dest }}/{{ app_version }}"
    version: "{{ app_version }}"
  when: not file_details.stat.exists

- name: Change ownership
  file:
    path: "{{ app_dest }}/{{ app_version }}"
    recurse: yes
    state: directory
    group: deployers
    mode: '0775'

- name: Add nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    group: deployers  # not fully secured solution
  notify:
    - Reload Nginx

- name: Add example config
  template:
    src: example.conf.j2
    dest: /etc/nginx/conf.d/example.conf
    group: deployers  # not fully secured solution
  notify:
    - Reload Nginx